from __future__ import annotations

from dataclasses import dataclass
import math
from typing import Iterable

import torch


@dataclass(frozen=True)
class PruningPlan:
    """Plan generated by attention-guided pruning."""

    per_layer_pruned_indices: list[list[int]]
    global_keep_indices: list[int]
    global_pruned_indices: list[int]
    token_importance: list[float]


@dataclass(frozen=True)
class LayerInterleavedPlan:
    """Execution order and critical-path lengths for layer scheduling."""

    order: list[int]
    critical_path: list[float]


def ilh_bounds(total_tokens: int, core_ratio: float = 0.70, important_ratio: float = 0.85) -> dict[str, int]:
    """
    Build ILH-Index tier bounds.

    Bounds are represented as prefix lengths over the sparse token axis:
    - core: [0, core)
    - important: [0, important)
    - optional: [0, optional)
    """
    total = max(0, int(total_tokens))
    if total == 0:
        return {"core": 0, "important": 0, "optional": 0}

    core = max(1, int(math.ceil(total * float(core_ratio))))
    important = max(core, int(math.ceil(total * float(important_ratio))))
    important = min(important, total)
    return {"core": core, "important": important, "optional": total}


def build_layer_interleaved_plan(
    load_times: Iterable[float],
    compute_times: Iterable[float],
) -> LayerInterleavedPlan:
    """
    Layer-Interleaved-Scheduler based on critical-path greedy order.

    cpl[l] = compute[l] + max(cpl[l-1], load[l])
    """
    loads = [max(0.0, float(x)) for x in load_times]
    computes = [max(0.0, float(x)) for x in compute_times]
    if len(loads) != len(computes):
        raise ValueError("load_times and compute_times must have the same length")

    n = len(loads)
    if n == 0:
        return LayerInterleavedPlan(order=[], critical_path=[])

    cpl = [0.0 for _ in range(n)]
    for i in range(n):
        prev = cpl[i - 1] if i > 0 else 0.0
        cpl[i] = computes[i] + max(prev, loads[i])

    order = sorted(range(n), key=lambda i: cpl[i], reverse=True)
    return LayerInterleavedPlan(order=order, critical_path=cpl)


def _normalize_scores(scores: torch.Tensor) -> torch.Tensor:
    scores = scores.float()
    if scores.numel() == 0:
        return scores
    min_v = torch.min(scores)
    max_v = torch.max(scores)
    span = max_v - min_v
    if float(span) <= 1e-8:
        return torch.full_like(scores, 1.0 / scores.numel())
    scaled = (scores - min_v) / span
    denom = torch.sum(scaled)
    if float(denom) <= 1e-8:
        return torch.full_like(scores, 1.0 / scores.numel())
    return scaled / denom


def build_attention_guided_pruning_plan(
    layer_scores: list[torch.Tensor],
    layer_keep_ratios: list[float] | None,
    text_token_len: int,
    global_keep_ratio: float | None = None,
    sink_token_idx: int = 0,
    local_window: int = 256,
    layer_blend: float = 0.25,
) -> PruningPlan:
    """
    Attention-Guided-KV-Pruning with cross-layer aggregation and protection rules.

    Inputs:
    - layer_scores[l]: token importance scores for layer l, shape [N_l]
      (typically derived from anchor-query attention)
    - layer_keep_ratios[l]: per-layer keep ratios in [0, 1]
    - text_token_len: only text tokens are eligible for pruning

    Outputs:
    - per-layer pruned indices (same cardinality for every layer)
    - global keep/pruned sets
    - normalized global token importance
    """
    num_layers = len(layer_scores)
    if num_layers == 0 or text_token_len <= 1:
        return PruningPlan(
            per_layer_pruned_indices=[[] for _ in range(num_layers)],
            global_keep_indices=[],
            global_pruned_indices=[],
            token_importance=[],
        )

    min_len = text_token_len
    for s in layer_scores:
        if s.numel() > 0:
            min_len = min(min_len, int(s.numel()))
    n = max(1, int(min_len))

    if layer_keep_ratios is None or len(layer_keep_ratios) != num_layers:
        layer_keep_ratios = [0.10 for _ in range(num_layers)]

    normalized: list[torch.Tensor] = []
    for s in layer_scores:
        if s.numel() == 0:
            cur = torch.zeros(n, dtype=torch.float32)
        else:
            cur = s[:n].detach().cpu().float().clamp_min(0.0)
        normalized.append(_normalize_scores(cur))

    stacked = torch.stack(normalized, dim=0)
    global_scores = torch.sum(stacked, dim=0)

    if global_keep_ratio is None:
        global_keep_ratio = float(sum(layer_keep_ratios) / max(1, len(layer_keep_ratios)))
    global_keep_ratio = max(0.01, min(0.99, float(global_keep_ratio)))

    target_keep = max(1, min(n, int(math.ceil(n * global_keep_ratio))))

    protected: set[int] = set()
    if n > 0:
        protected.add(max(0, min(n - 1, int(sink_token_idx))))
    if local_window > 0:
        start = max(0, n - int(local_window))
        protected.update(range(start, n))

    keep_set = set(protected)
    ranked = torch.argsort(global_scores, descending=True)
    for idx_t in ranked.tolist():
        if len(keep_set) >= target_keep:
            break
        keep_set.add(int(idx_t))

    target_keep = max(target_keep, len(keep_set))

    global_keep = sorted(keep_set)
    global_pruned = sorted(set(range(n)) - keep_set)

    per_layer_pruned: list[list[int]] = []
    blend = max(0.0, float(layer_blend))
    for layer_idx in range(num_layers):
        layer_scores_norm = normalized[layer_idx]
        mixed = global_scores + blend * layer_scores_norm
        ranked_layer = torch.argsort(mixed, descending=True)
        layer_keep = set(protected)
        for idx_t in ranked_layer.tolist():
            if len(layer_keep) >= target_keep:
                break
            layer_keep.add(int(idx_t))

        layer_pruned = sorted(set(range(n)) - layer_keep)
        per_layer_pruned.append(layer_pruned)

    return PruningPlan(
        per_layer_pruned_indices=per_layer_pruned,
        global_keep_indices=global_keep,
        global_pruned_indices=global_pruned,
        token_importance=global_scores.tolist(),
    )
